#version 450

#include"prelude.comp"


#define TAU (2*3.1415926538)

void main() {
    uint i = gl_GlobalInvocationID.x;

    uint x = i % WIDTH;
    uint y = i / WIDTH;

    float fx = dx * x;
    float fy = dy * y;

    // vx_arr[i] = sin(fx * TAU) + cos(2 * fy * TAU);
    // vy_arr[i] = 2 * cos(fx * TAU) + cos(3 * fy * TAU);
    if (1.5 < fx && fx < 3.5 && 1.5 < fy && fy < 3.5) {
        vx_arr[i] = 1;
        vy_arr[i] = -(fy - 2.5);
    }
}
